/*
 Copyright (c) 2000-2005 University of Washington.  All rights reserved.

 Redistribution and use of this distribution in source and binary forms,
 with or without modification, are permitted provided that:

   The above copyright notice and this permission notice appear in
   all copies and supporting documentation;

   The name, identifiers, and trademarks of the University of Washington
   are not used in advertising or publicity without the express prior
   written permission of the University of Washington;

   Recipients acknowledge that this distribution is made available as a
   research courtesy, "as is", potentially with defects, without
   any obligation on the part of the University of Washington to
   provide support, services, or repair;

   THE UNIVERSITY OF WASHINGTON DISCLAIMS ALL WARRANTIES, EXPRESS OR
   IMPLIED, WITH REGARD TO THIS SOFTWARE, INCLUDING WITHOUT LIMITATION
   ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
   PARTICULAR PURPOSE, AND IN NO EVENT SHALL THE UNIVERSITY OF
   WASHINGTON BE LIABLE FOR ANY SPECIAL, INDIRECT OR CONSEQUENTIAL
   DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR
   PROFITS, WHETHER IN AN ACTION OF CONTRACT, TORT (INCLUDING
   NEGLIGENCE) OR STRICT LIABILITY, ARISING OUT OF OR IN CONNECTION WITH
   THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */
package org.bedework.dumprestore.dump;

import org.bedework.appcommon.configs.DumpRestoreConfig;
import org.bedework.calenv.CalOptions;
import org.bedework.dumprestore.Defs;
import org.bedework.dumprestore.dump.dumpling.DumpAll;

import java.io.FileWriter;
import java.io.OutputStreamWriter;

import org.apache.log4j.Logger;

/** Application to dump calendar data.
 *
 * @author Mike Douglass   douglm@rpi.edu
 * @version 3.1
 */
public class Dump implements Defs {
  private transient Logger log;

  /* Properties can be supplied via the command line or via a the properties
   * file with the prefix propertyPrefix + appName + "."
   */
  private String appPrefix = "org.bedework.app.";

  private String appName;

  DumpIntf di;

  /* Runtime arg -f Where we dump to.
   */
  private String fileName;

  /* runtime arg -i (id) */
  //private String id = "sa";

  String indent = "";

  private DumpGlobals globals = new DumpGlobals();

  Dump() throws Throwable {
  }

  void open() throws Throwable {
    di = new HibDump(globals.config.getDebug());

    if (fileName == null) {
      globals.out = new OutputStreamWriter(System.out);
    } else {
      globals.out = new FileWriter(fileName);
    }
  }

  void close() throws Throwable {
    globals.out.close();
  }

  void doDump() throws Throwable {

    new DumpAll(globals, di).dumpSection(null);
  }

  void stats() {
    globals.stats();
  }


  void processArgs(String[] args) throws Throwable {
    /* Look for appname arg */

    for (int i = 0; i < args.length; i++) {
      if (args[i].equals("-debug")) {
        globals.config.setDebug(true);
      } else if (args[i].equals("-ndebug")) {
        globals.config.setDebug(false);
      } else if (args[i].equals("")) {
        // null arg generated by ant
      } else if (args[i].equals("-noarg")) {
        // noop
      } else if (argpar("-appname", args, i)) {
        i++;
        // done earlier
      } else if (argpar("-f", args, i)) {
        i++;
        fileName = args[i];
      } else if (argpar("-i", args, i)) {
        i++;
        //id = args[i];
      } else {
        error("Illegal argument: " + args[i]);
        throw new Exception("Invalid args");
      }
    }
  }

  boolean argpar(String n, String[] args, int i) throws Exception {
    if (!args[i].equals(n)) {
      return false;
    }

    if ((i + 1) == args.length) {
      throw new Exception("Invalid args");
    }
    return true;
  }

  void getConfigProperties(String[] args) throws Throwable {
    /* Look for the appname arg */

    if (args != null) {
      for (int i = 0; i < args.length; i++) {
        if (argpar("-appname", args, i)) {
          i++;
          appName = args[i];
          break;
        }
      }
    }

    if (appName == null) {
      error("Missing required argument -appname");
      throw new Exception("Invalid args");
    }

    globals.init((DumpRestoreConfig)CalOptions.getProperty(appPrefix + appName));
  }

  protected Logger getLog() {
    if (log == null) {
      log = Logger.getLogger(this.getClass());
    }

    return log;
  }

  protected void error(String msg) {
    getLog().error(msg);
  }

  protected void info(String msg) {
    getLog().info(msg);
  }

  protected void trace(String msg) {
    getLog().debug(msg);
  }

  /**
   * @param args
   */
  public static void main(String[] args) {
    Dump d = null;

    try {
      long startTime = System.currentTimeMillis();

      d = new Dump();

      d.getConfigProperties(args);

      d.processArgs(args);

      d.open();

      d.doDump();

      d.stats();

      long millis = System.currentTimeMillis() - startTime;
      long seconds = millis / 1000;
      long minutes = seconds / 60;
      seconds -= (minutes * 60);

      d.info("Elapsed time: " + minutes + ":" + twoDigits(seconds));
    } catch (Throwable t) {
      t.printStackTrace();
    } finally {
      try {
        d.close();
      } catch (Throwable t1) {
        t1.printStackTrace();
      }
    }
  }

  private static String twoDigits(long val) {
    if (val < 10) {
      return "0" + val;
    }

    return String.valueOf(val);
  }
}
