#! /bin/bash -f

# data was generated by taking the Berkeley data and putting it through `grep '^[a-zA-Z ]* ([0-9]*)'`
# to get records that are likely to be a building and a room number.
#

FS='|'
INFILE=BerkeleyLocRecords.txt
LDAPOUT=ldapOut
VCARDOUT=vcardOut
LDAPSetLines="objectclass: top
objectclass: calendarresource
objectclass: admittanceinfo
objectclass: inventoryinfo
objectclass: schedapprovalinfo
objectclass: calendarresourcecost"
VCARDHeader="BEGIN:VCARD
   VERSION:4.0"
VCARDFooter="   END:VCARD"
uidPrefix="bw"
uidSuffix="@berkeley.edu"

cp /dev/null $LDAPOUT
cp /dev/null $VCARDOUT



counter=0
while read line; do
	buildPerson="false"	
	counter=`expr $counter + 1`
	
	
	#F1 => room description
	F1=$(echo $line|cut -d $FS -f 1)
	# we'll hack together a cn/FN out of the description.
	cn=`echo $F1 | sed 's/ Hall//;s/ Building//;s/ Center//;s/ Bldg//' \
	    | sed 's/ Student Ctr//;s/ Media Room//;s/ Art History Seminar Room//;s/ Place//' \
	    | cut -d \| -f1 | cut -d ')' -f1 \
	    | sed 's/ //g;s/(//'`
	
	F2=$(echo $line|cut -d $FS -f 2)
	#F3 => capacity/CAPACITY
	F3=$(echo $line|cut -d $FS -f 3)
	#F4 => last name of room manager
	F4=$(echo $line|cut -d $FS -f 4)
	#F5 => first name of room manager
	F5=$(echo $line|cut -d $FS -f 5)
	if [ $F5 != "" ]; then
		buildPersion="true"
		roomManager=${F5}${F4}
    fi
	#F6 => phone number of room manager
	F6=$(echo $line|cut -d $FS -f 6)
	#F7 => fax number of room manager
	F7=$(echo $line|cut -d $FS -f 7)
	#F8 => email of room manager
	F8=$(echo $line|cut -d $FS -f 8)
	#F9 => 
	F9=$(echo $line|cut -d $FS -f 9)
	F10=$(echo $line|cut -d $FS -f10)
	#F11 Requires Approval
	F11=$(echo $line|cut -d $FS -f11)
	if [ "$F11" = "" ]; then
	  autoaccept=true
	else
	  autoaccept=false
	fi
	F12=$(echo $line|cut -d $FS -f12)
	F13=$(echo $line|cut -d $FS -f13)
	
	#generate UID
	case $counter in
		?) normalizedCounter="00000${counter}"
		   ;;
		??) normalizedCounter="0000${counter}"
	       ;;
	    ???) normalizedCounter="000${counter}"
	       ;;
	esac
	uid="${uidPrefix}${normalizedCounter}${uidSuffix}"

    # If no info on autoaccept, turn it on.	
	if [ "$F12" = "" ]; then 
		F12="true"
	fi
	
#### locations
	
    #LDAP
echo "dn: cn=$cn,ou=locations,dc=berkeley,dc=edu
$LDAPSetLines
calresourcekind: location
uid: $uid
cn: $cn
ou: locations
description: $F1" >> $LDAPOUT
  if [ "$F3" != "" ]; then
    echo "capacity: $F3" >> $LDAPOUT
  fi
  echo "autoaccept: $autoaccept
" >> $LDAPOUT

    #VCARD
  echo "$VCARDHeader
   UID:urn:uuid:$uid
   KIND: location
   FN: $cn
   ORG: locations
   NOTE: $F1
   CAPACITY: $F3
   AUTOACCEPT: $autoaccept
$VCARDFooter
" >> $VCARDOUT

  ### people
  if [ $buildPerson = "true" ]; then
	name="$F"
	echo "dn: cn=${roomManager}, ou=people,dc=berkeley,dc=edu	
  fi

done < $INFILE


