/*
 Copyright (c) 2000-2005 University of Washington.  All rights reserved.

 Redistribution and use of this distribution in source and binary forms,
 with or without modification, are permitted provided that:

   The above copyright notice and this permission notice appear in
   all copies and supporting documentation;

   The name, identifiers, and trademarks of the University of Washington
   are not used in advertising or publicity without the express prior
   written permission of the University of Washington;

   Recipients acknowledge that this distribution is made available as a
   research courtesy, "as is", potentially with defects, without
   any obligation on the part of the University of Washington to
   provide support, services, or repair;

   THE UNIVERSITY OF WASHINGTON DISCLAIMS ALL WARRANTIES, EXPRESS OR
   IMPLIED, WITH REGARD TO THIS SOFTWARE, INCLUDING WITHOUT LIMITATION
   ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
   PARTICULAR PURPOSE, AND IN NO EVENT SHALL THE UNIVERSITY OF
   WASHINGTON BE LIABLE FOR ANY SPECIAL, INDIRECT OR CONSEQUENTIAL
   DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR
   PROFITS, WHETHER IN AN ACTION OF CONTRACT, TORT (INCLUDING
   NEGLIGENCE) OR STRICT LIABILITY, ARISING OUT OF OR IN CONNECTION WITH
   THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */
/* **********************************************************************
    Copyright 2005 Rensselaer Polytechnic Institute. All worldwide rights reserved.

    Redistribution and use of this distribution in source and binary forms,
    with or without modification, are permitted provided that:
       The above copyright notice and this permission notice appear in all
        copies and supporting documentation;

        The name, identifiers, and trademarks of Rensselaer Polytechnic
        Institute are not used in advertising or publicity without the
        express prior written permission of Rensselaer Polytechnic Institute;

    DISCLAIMER: The software is distributed" AS IS" without any express or
    implied warranty, including but not limited to, any implied warranties
    of merchantability or fitness for a particular purpose or any warrant)'
    of non-infringement of any current or pending patent rights. The authors
    of the software make no representations about the suitability of this
    software for any particular purpose. The entire risk as to the quality
    and performance of the software is with the user. Should the software
    prove defective, the user assumes the cost of all necessary servicing,
    repair or correction. In particular, neither Rensselaer Polytechnic
    Institute, nor the authors of the software are liable for any indirect,
    special, consequential, or incidental damages related to the software,
    to the maximum extent the law permits.
*/

package org.bedework.appcommon;

import org.bedework.calfacade.BwCalendar;
import org.bedework.calfacade.CalFacadeException;
import org.bedework.icalendar.IcalTranslator;
import org.bedework.icalendar.IcalUtil;

import edu.rpi.sss.util.xml.XmlUtil;

import net.fortuna.ical4j.model.Calendar;
import net.fortuna.ical4j.model.ComponentList;
import net.fortuna.ical4j.model.Property;
import net.fortuna.ical4j.model.component.VTimeZone;

import java.io.Reader;
import java.io.Serializable;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.util.Collection;
import java.util.Iterator;
import java.util.Vector;

import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;

import org.apache.log4j.Logger;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.xml.sax.InputSource;
import org.xml.sax.SAXException;

/** This class is used by clients and applications to parse the timezone
 * information generated by the timezone tool.
 *
 * @author  Mike Douglass douglm @ rpi.edu
 */
public class TimeZonesParser implements Serializable {
  private boolean debug;

  private InputStream inStr;

  private transient Logger log;

  /** Result class
   */
  public static class TimeZoneInfo {
    /** */
    public String tzid;
    /** */
    public VTimeZone timezone;
  }

  /** Constructor
   *
   * @param inStr
   * @param debug
   */
  public TimeZonesParser(InputStream inStr, boolean debug) {
    this.inStr = inStr;
    this.debug = debug;
  }

  /** Return a collection of TimeZoneInfo
   *
   * @return Collection of TimeZoneInfo
   * @throws CalFacadeException
   */
  public Collection getTimeZones() throws CalFacadeException {
    /* The input file should look something like:
    <dir>
      <name>A-name</name>
      <dir>...</dir>
      <file>
        <name>file1.ics</name>
        <data>...</data>
      </file>
    </dir>

    We ignore the first name - it represents the root.
    Each <dir> element may contain other <dir> and <file> elements.
    Each <name> element is a path element
  */

    DirClass rootDir = parseTzDefs(new InputStreamReader(inStr));

    Vector v = new Vector();

    doDir(v, rootDir, "");

    return v;
  }

  private String doDir(Vector v, DirClass dir, String indent) throws CalFacadeException {
    if (debug) {
      trace(indent + "Dir: " + dir.cal.getName());
    }

    Iterator dit = dir.dirs.iterator();
    while (dit.hasNext()) {
      doDir(v, (DirClass)dit.next(), indent + "  ");
    }

    Iterator tzit = dir.tzs.iterator();
    while (tzit.hasNext()) {
      Calendar ical = (Calendar)tzit.next();

      ComponentList cl = ical.getComponents();

      if (cl.size() != 1) {
        throw new CalFacadeException(CalFacadeException.timezonesReadError,
                                     cl.size() + " components in Calendar");
      }

      Object o = cl.get(0);
      if (!(o instanceof VTimeZone)) {
        throw new CalFacadeException(CalFacadeException.timezonesReadError,
                                     "component in Calendar not VTimeZone");
      }

      TimeZoneInfo tzi = new TimeZoneInfo();

      tzi.timezone = (VTimeZone)o;
      tzi.tzid = IcalUtil.getProperty(tzi.timezone, Property.TZID).getValue();

      v.add(tzi);

      if (debug) {
        trace(indent + "tzid: " + tzi.tzid);
      }
    }

    return null;
  }

  private static class DirClass {
    BwCalendar cal; // The name will be set according to the dir/name

    Collection dirs = new Vector();

    /* Collection of Calendar obects
     */
    Collection tzs = new Vector();
  }

  private DirClass parseTzDefs(Reader rdr) throws CalFacadeException {
    Document doc = null;

    try {
      DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
      factory.setNamespaceAware(false);

      DocumentBuilder builder = factory.newDocumentBuilder();

      doc = builder.parse(new InputSource(rdr));
    } catch (SAXException e) {
      throw new CalFacadeException(CalFacadeException.timezonesReadError,
                                   e.getMessage());
    } catch (Throwable t) {
      throw new CalFacadeException(CalFacadeException.timezonesReadError,
                                   t.getMessage());
    } finally {
      if (rdr != null) {
        try {
          rdr.close();
        } catch (Throwable t) {}
      }
    }

    return processDir(doc.getDocumentElement());
  }

  private DirClass processDir(Element dir) throws CalFacadeException {
    try {
      DirClass d = new DirClass();
      Collection children = XmlUtil.getElements(dir);

      Iterator it = children.iterator();

      /* First is name */

      Element nmel = (Element)it.next();

      d.cal = new BwCalendar();
      d.cal.setName(XmlUtil.getElementContent(nmel));

      while (it.hasNext()) {
        Element el = (Element)it.next();

        if ("dir".equals(el.getTagName())) {
          d.dirs.add(processDir(el));
        } else if ("file".equals(el.getTagName())) {
          d.tzs.add(processFile(el));
        } else {
          throw new CalFacadeException(CalFacadeException.timezonesReadError,
              "Expected <dir> or <file>, found: " + el.getTagName());
        }
      }

      return d;
    } catch (CalFacadeException cfe) {
      throw cfe;
    } catch (Throwable t) {
      throw new CalFacadeException(t);
    }
  }

  private Calendar processFile(Element ics) throws CalFacadeException {
    //NodeList ds = ics.getElementsByTagName("data");

    try {
      Collection children = XmlUtil.getElements(ics);

      Iterator it = children.iterator();

      /* First is name */

      Element el = (Element)it.next();
      if (!"name".equals(el.getTagName())) {
        throw new CalFacadeException(CalFacadeException.timezonesReadError,
            "Expected <name>, found: " + el.getTagName());
      }

      /* Next is data */
      el = (Element)it.next();
      if (!"data".equals(el.getTagName())) {
        throw new CalFacadeException(CalFacadeException.timezonesReadError,
            "Expected <data>, found: " + el.getTagName());
      }

      return IcalTranslator.getCalendar(XmlUtil.getElementContent(el));
    } catch (CalFacadeException cfe) {
      throw cfe;
    } catch (Throwable t) {
      throw new CalFacadeException(t);
    }
  }

  /** Get a logger for messages
   */
  protected Logger getLogger() {
    if (log == null) {
      log = Logger.getLogger(this.getClass());
    }

    return log;
  }

  protected void trace(String msg) {
    getLogger().debug(msg);
  }
}

