/*
 Copyright (c) 2000-2005 University of Washington.  All rights reserved.

 Redistribution and use of this distribution in source and binary forms,
 with or without modification, are permitted provided that:

   The above copyright notice and this permission notice appear in
   all copies and supporting documentation;

   The name, identifiers, and trademarks of the University of Washington
   are not used in advertising or publicity without the express prior
   written permission of the University of Washington;

   Recipients acknowledge that this distribution is made available as a
   research courtesy, "as is", potentially with defects, without
   any obligation on the part of the University of Washington to
   provide support, services, or repair;

   THE UNIVERSITY OF WASHINGTON DISCLAIMS ALL WARRANTIES, EXPRESS OR
   IMPLIED, WITH REGARD TO THIS SOFTWARE, INCLUDING WITHOUT LIMITATION
   ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
   PARTICULAR PURPOSE, AND IN NO EVENT SHALL THE UNIVERSITY OF
   WASHINGTON BE LIABLE FOR ANY SPECIAL, INDIRECT OR CONSEQUENTIAL
   DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR
   PROFITS, WHETHER IN AN ACTION OF CONTRACT, TORT (INCLUDING
   NEGLIGENCE) OR STRICT LIABILITY, ARISING OUT OF OR IN CONNECTION WITH
   THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */
/* **********************************************************************
    Copyright 2005 Rensselaer Polytechnic Institute. All worldwide rights reserved.

    Redistribution and use of this distribution in source and binary forms,
    with or without modification, are permitted provided that:
       The above copyright notice and this permission notice appear in all
        copies and supporting documentation;

        The name, identifiers, and trademarks of Rensselaer Polytechnic
        Institute are not used in advertising or publicity without the
        express prior written permission of Rensselaer Polytechnic Institute;

    DISCLAIMER: The software is distributed" AS IS" without any express or
    implied warranty, including but not limited to, any implied warranties
    of merchantability or fitness for a particular purpose or any warrant)'
    of non-infringement of any current or pending patent rights. The authors
    of the software make no representations about the suitability of this
    software for any particular purpose. The entire risk as to the quality
    and performance of the software is with the user. Should the software
    prove defective, the user assumes the cost of all necessary servicing,
    repair or correction. In particular, neither Rensselaer Polytechnic
    Institute, nor the authors of the software are liable for any indirect,
    special, consequential, or incidental damages related to the software,
    to the maximum extent the law permits.
*/
package org.bedework.mail;

import java.net.URLDecoder;
import java.net.URLEncoder;

/** This represents an attachments as a path to a file containing the
 * content and the original filename.
 *
 * @author Mike Douglass douglm@rpi.edu
 */
public class FileAttachment implements Attachment {
  /**
   *
   * @serial
   */
  private String dataPath;

  /**
   *
   * @serial
   */
  private String originalName;

  /**
   *
   */
  public FileAttachment() {
  }

  /**
   * @param dataPath
   * @param originalName
   */
  public FileAttachment(String dataPath, String originalName) {
    this.dataPath = dataPath;
    this.originalName = originalName;
  }

  /**
   * @param val
   */
  public void setDataPath(String val) {
    dataPath = val;
  }

  /**
   * @return String
   */
  public String getDataPath() {
    return dataPath;
  }

  /**
   * @param val
   */
  public void setOriginalName(String val) {
    originalName = val;
  }

  /**
   * @return original name
   */
  public String getOriginalName() {
    return originalName;
  }

  /** Return an object based on the value which must be of the form:
   *  generated by toString.
   *
   * @param val          String representation of object.
   * @return FileAttachment    object.
   */
  public static FileAttachment fromString(String val) {
    if (! val.startsWith("FileAttachment[")) {
      throw new RuntimeException(
            "FileAttachment.fromString, bad value: " + val);
    }

    int start = val.indexOf("[");
    int gap = val.indexOf(" ");
    int end = val.indexOf("]");

    if ((gap < 0) || (end < 0)) {
      throw new RuntimeException(
            "FileAttachment.fromString, bad value: " + val);
    }

    FileAttachment mma;

    try {
      mma = new FileAttachment(
            URLDecoder.decode(val.substring(start + 1, gap), "UTF-8"),
            URLDecoder.decode(val.substring(gap + 1, end), "UTF-8"));
    } catch (Throwable t) {
      throw new RuntimeException(
            "FileAttachment.fromString, bad value: " + val);
    }

    return mma;
  }

  /** Return a value of the form:
   *   FileAttachment[dataPath originalName]
   * where originalName and dataPath are encoded using URLEncoder.
   *
   * @return String    representation of object.
   */
  public String toString() {
    StringBuffer sb = new StringBuffer("FileAttachment[");

    try {
      sb.append(URLEncoder.encode(dataPath, "UTF-8"));
      sb.append(" ");
      sb.append(URLEncoder.encode(originalName, "UTF-8"));
      sb.append("]");
    } catch (Throwable t) {
      throw new RuntimeException(t);
    }

    return sb.toString();
  }

  public boolean equals(Object val) {
    if (this == val) {
      return true;
    }

    if (!(val instanceof FileAttachment)) {
      return false;
    }

    FileAttachment that = (FileAttachment)val;

    return that.getDataPath().equals(getDataPath())
            && that.getOriginalName().equals(getOriginalName());
  }

  /** Try it
   * @param args
   */
  public static void main(String[] args) {
    try {
      FileAttachment mma;
      FileAttachment mma1;

      mma = new FileAttachment("easy/path/to/file", "easyname");

      System.out.println("Try an easy one");
      System.out.println(mma);
      mma1 = fromString(mma.toString());
      System.out.println(mma1);
      System.out.println(mma1.getDataPath());
      System.out.println(mma1.getOriginalName());
      System.out.println("equals: " + mma.equals(mma1));

      mma = new FileAttachment("harder/pa th/to/file[]",
                                    "name with blank[s] and space(s)");

      System.out.println("\nTry a harder one");
      System.out.println(mma);
      mma1 = fromString(mma.toString());
      System.out.println(mma1);
      System.out.println(mma1.getDataPath());
      System.out.println(mma1.getOriginalName());
      System.out.println("equals: " + mma.equals(mma1));
    } catch (Throwable t) {
      t.printStackTrace();
    }
  }
}

